url: https://toolkit.occrp.org/
title: OCCRP toolkit
metatitle: "journalist's toolkit"
author: Organized Crime and Corruption Reporting Project
description: >
  The investigative toolkit brings together technologies and services that
  support journalists doing cross-border research. Toolkit includes a
  staffed research desk, data search engine, and collaboration tools.
logo: /static/svg/logo.svg
google_analytics: ""
repository_url: https://git.occrp.org/websites/toolkit.occrp.org

autoprefixer:
  browsers:
    - last 2 versions

highlighter: pygments
# paginate: 7

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-typogrify
  - jekyll-redirect-from



exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - Makefile
  - .editorconfig
  - .dockerignore
  - .gitignore
  - .git
  - vendor
  - .sass-cache
  - _contrib
  - .gitlab-ci.yml
